import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, CalendarDays, CheckCircle2, Clock3, MapPin, Star, UserRound } from 'lucide-react';
import api from '../services/api';
import Loader from '../components/Loader';

export default function ServiceDetails() {
  const { id } = useParams(); const [service, setService] = useState(); const [error, setError] = useState('');
  useEffect(() => { api.get(`/services/${id}`).then(({ data }) => setService(data.service)).catch(e => setError(e.response?.data?.message || 'Could not find this service.')); }, [id]);
  if (error) return <main className="container-page py-20 text-center"><h1 className="text-3xl">{error}</h1><Link className="btn-primary mt-6" to="/services">Back to services</Link></main>;
  if (!service) return <Loader/>;
  const provider = service.providerId?.name || service.providerName || 'ServiceHub Pro';
  return <main className="container-page py-10 sm:py-16"><Link to="/services" className="mb-7 inline-flex items-center gap-2 text-sm font-bold text-slate-600 hover:text-brand"><ArrowLeft size={17}/> All services</Link><div className="grid gap-10 lg:grid-cols-2"><img className="h-[330px] w-full rounded-3xl object-cover sm:h-[480px]" src={service.image} alt=""/><div className="flex flex-col"><span className="w-fit rounded-full bg-sage px-3 py-1 text-xs font-bold text-brand">{service.category}</span><h1 className="mt-4 text-5xl leading-tight">{service.title}</h1><div className="mt-4 flex items-center gap-1 font-semibold text-slate-600"><Star size={18} className="fill-accent text-accent"/> {service.rating?.toFixed(1)} <span className="ml-1 font-normal">({service.reviewCount || 0} reviews)</span></div><p className="mt-7 text-lg leading-8 text-slate-600">{service.description}</p><div className="my-8 grid gap-4 border-y border-slate-100 py-5 sm:grid-cols-3"><div><span className="text-sm text-slate-500">Starting at</span><p className="text-2xl font-bold text-brand">${service.price}</p></div><div className="flex items-center gap-2 text-sm font-semibold text-slate-600"><Clock3 className="text-brand" size={18}/>{service.duration || 60} min</div><div className="flex items-center gap-2 text-sm font-semibold text-slate-600"><MapPin className="text-brand" size={18}/>{service.location || 'Local area'}</div></div><div className="rounded-xl bg-sage p-4 text-sm text-slate-700"><p className="flex items-center gap-2 font-bold"><UserRound size={17} className="text-brand"/>{provider}</p><p className="mt-1 text-slate-600">Local verified service provider</p></div><div className="mt-6"><p className="text-sm font-bold text-slate-700">Available time slots</p><div className="mt-2 flex flex-wrap gap-2">{(service.availableSlots || []).map(slot => <span key={slot} className="rounded-lg bg-sage px-3 py-2 text-sm font-semibold text-brand">{slot}</span>)}</div></div><div className="mt-6 space-y-3 text-sm font-medium text-slate-600"><p className="flex gap-2"><CheckCircle2 className="text-brand" size={18}/> Vetted local professionals</p><p className="flex gap-2"><CheckCircle2 className="text-brand" size={18}/> Convenient scheduling</p></div><Link to={`/book/${service._id}`} className="btn-primary mt-8 w-full sm:w-fit"><CalendarDays size={18}/> Book now</Link></div></div></main>;
}
